name: Bundle and release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout theme
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build and bundle theme into .asar
        run: bun run build:asar

      - name: Release bundled asar, json, and theme.css
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bundle/*, *.theme.css"
          makeLatest: true
          generateReleaseNotes: true
